# Generated by Django 3.1.2 on 2021-03-02 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms_app', '0004_auto_20210228_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Lecturer'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='lms_app.faculty', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='subject',
            field=models.ManyToManyField(related_name='student_subject', to='lms_app.Subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
    ]
