# Generated by Django 3.1.7 on 2021-03-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_auto_20210302_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='lecturerprofile',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=8, verbose_name='Salary'),
        ),
    ]
