# Generated by Django 3.1.2 on 2021-02-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Last Name'),
        ),
    ]
